"""
BrewTrade AI - Documents router.
Export docs, statements, commercial invoices, CARICOM, shipping.
"""
import os
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse, Response
from sqlalchemy import func
from sqlalchemy.orm import Session

from database import get_db
from models import Document


router = APIRouter(prefix="/api/documents", tags=["Documents"])


# Friendly labels for document folder display
DOC_TYPE_LABELS = {
    "export": "Export Documents",
    "statement": "Account Statements",
    "commercial_invoice": "Commercial Invoices",
    "caricom": "CARICOM Certificates",
    "shipping": "Shipping Documents",
}


def _label_for(doc_type: str) -> str:
    return DOC_TYPE_LABELS.get(doc_type, doc_type.replace("_", " ").title())


def _placeholder_text(doc: Document) -> str:
    """Generate a deterministic text placeholder for documents lacking a real file."""
    return (
        f"BrewTrade AI - {_label_for(doc.doc_type)}\n"
        f"========================================\n"
        f"Title       : {doc.title}\n"
        f"Filename    : {doc.filename}\n"
        f"Document ID : {doc.id}\n"
        f"Customer ID : {doc.customer_id}\n"
        f"Issued      : {doc.created_at.isoformat() if doc.created_at else ''}\n\n"
        "This is a generated POC placeholder document. In production this would "
        "be the rendered PDF artifact (commercial invoice, CARICOM origin "
        "certificate, monthly statement, etc.) generated by the document "
        "service and stored in object storage.\n"
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@router.get("/ping")
def ping():
    return {"status": "ok", "module": "documents"}


@router.get("")
@router.get("/")
def list_documents(
    customer_id: Optional[int] = Query(None),
    doc_type: Optional[str] = Query(None),
    db: Session = Depends(get_db),
) -> Dict[str, Any]:
    """List documents with optional filters; response is grouped by doc_type."""
    q = db.query(Document)
    if customer_id is not None:
        q = q.filter(Document.customer_id == customer_id)
    if doc_type:
        q = q.filter(Document.doc_type == doc_type)
    docs = q.order_by(Document.created_at.desc()).all()

    groups: Dict[str, Dict[str, Any]] = {}
    for d in docs:
        bucket = groups.setdefault(
            d.doc_type,
            {
                "doc_type": d.doc_type,
                "label": _label_for(d.doc_type),
                "count": 0,
                "documents": [],
            },
        )
        bucket["count"] += 1
        bucket["documents"].append(
            {
                "id": d.id,
                "customer_id": d.customer_id,
                "doc_type": d.doc_type,
                "filename": d.filename,
                "title": d.title,
                "created_at": d.created_at,
                "file_path": d.file_path,
            }
        )

    return {
        "total": len(docs),
        "filters": {"customer_id": customer_id, "doc_type": doc_type},
        "groups": list(groups.values()),
    }


@router.get("/folders")
def list_folders(
    customer_id: Optional[int] = Query(None),
    db: Session = Depends(get_db),
) -> List[Dict[str, Any]]:
    """Folder structure: one entry per doc_type with count and latest date."""
    q = db.query(
        Document.doc_type,
        func.count(Document.id).label("count"),
        func.max(Document.created_at).label("latest_date"),
    )
    if customer_id is not None:
        q = q.filter(Document.customer_id == customer_id)
    rows = q.group_by(Document.doc_type).all()

    folders = [
        {
            "doc_type": doc_type,
            "label": _label_for(doc_type),
            "count": int(count or 0),
            "latest_date": latest_date,
        }
        for doc_type, count, latest_date in rows
    ]
    # Stable ordering: known types first in label order, then alpha
    known_order = list(DOC_TYPE_LABELS.keys())
    folders.sort(
        key=lambda f: (
            known_order.index(f["doc_type"]) if f["doc_type"] in known_order else 999,
            f["doc_type"],
        )
    )
    return folders


@router.get("/search")
def search_documents(
    q: str = Query(..., min_length=1, description="Search query"),
    customer_id: Optional[int] = Query(None),
    db: Session = Depends(get_db),
) -> List[Dict[str, Any]]:
    """Search documents by title or filename (case-insensitive ILIKE)."""
    pattern = f"%{q}%"
    query = db.query(Document).filter(
        (Document.title.ilike(pattern)) | (Document.filename.ilike(pattern))
    )
    if customer_id is not None:
        query = query.filter(Document.customer_id == customer_id)
    docs = query.order_by(Document.created_at.desc()).limit(100).all()
    return [
        {
            "id": d.id,
            "customer_id": d.customer_id,
            "doc_type": d.doc_type,
            "label": _label_for(d.doc_type),
            "filename": d.filename,
            "title": d.title,
            "created_at": d.created_at,
        }
        for d in docs
    ]


@router.get("/{doc_id}/preview")
def preview_document(doc_id: int, db: Session = Depends(get_db)) -> Dict[str, Any]:
    """Return metadata + a short text preview (200 chars)."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    preview_text = ""
    if doc.file_path and os.path.isfile(doc.file_path):
        try:
            with open(doc.file_path, "r", encoding="utf-8", errors="ignore") as fh:
                preview_text = fh.read(2000)
        except Exception:
            preview_text = ""

    if not preview_text:
        preview_text = _placeholder_text(doc)

    return {
        "id": doc.id,
        "customer_id": doc.customer_id,
        "doc_type": doc.doc_type,
        "label": _label_for(doc.doc_type),
        "filename": doc.filename,
        "title": doc.title,
        "created_at": doc.created_at,
        "file_path": doc.file_path,
        "preview": preview_text[:200],
    }


@router.get("/{doc_id}/download")
def download_document(doc_id: int, db: Session = Depends(get_db)):
    """Download the document file, or a generated text placeholder."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    if doc.file_path and os.path.isfile(doc.file_path):
        return FileResponse(
            path=doc.file_path,
            filename=doc.filename,
            media_type="application/octet-stream",
        )

    # File missing - generate a text placeholder so the UX never breaks.
    fallback_name = doc.filename if doc.filename else f"document-{doc.id}.txt"
    if not fallback_name.lower().endswith(".txt"):
        fallback_name = f"{os.path.splitext(fallback_name)[0]}.txt"
    body = _placeholder_text(doc)
    return Response(
        content=body,
        media_type="text/plain",
        headers={
            "Content-Disposition": f'attachment; filename="{fallback_name}"',
        },
    )
